--建表
--在FUSER的用户中
--student
CREATE TABLE "FUSER"."STUDENT"
  (
    "SID"   NUMBER NOT NULL ENABLE,
    "SNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "SAGE"  NUMBER NOT NULL ENABLE,
    "SSEX"  VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "STUDENT_PK" PRIMARY KEY ("SID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;
--course
CREATE TABLE "FUSER"."COURSE"
  (
    "CID"   NUMBER NOT NULL ENABLE,
    "CNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "TID"   NUMBER NOT NULL ENABLE,
    CONSTRAINT "COURSE_PK" PRIMARY KEY ("CID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;
--teacher
CREATE TABLE "FUSER"."TEACHER"
  (
    "TID"   NUMBER NOT NULL ENABLE,
    "TNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "TEACHER_PK" PRIMARY KEY ("TID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;
--sc
CREATE TABLE "FUSER"."SC"
  (
    "SID"   NUMBER NOT NULL ENABLE,
    "CID"   NUMBER NOT NULL ENABLE,
    "SCORE" NUMBER NOT NULL ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "SYSTEM" ;